#
# Copyright (C) 2026 gnrsbassoutlook
#
# This is free software, licensed under the MIT License.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-adhfilter
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_LICENSE:=MIT
PKG_MAINTAINER:=gnrsbassoutlook

LUCI_TITLE:=AdhFilter - 按设备管理 AdGuard Home 过滤
LUCI_DESCRIPTION:=Give /usr/bin/adhfilter a web UI: list devices, pin IP, \
 join/leave the filtering list, rename, self-check.
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# $(call BuildPackage,$(PKG_NAME))
